<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion> <!-- Or a specific version like 10.0 -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.8.0" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TypeScriptGenerator\TypeScriptGenerator.fsproj" />
  </ItemGroup>

</Project>
